import "dotenv/config";
import { readFileSync, existsSync } from "fs";

// Verifies production onboarding against the RUNNING app (default
// http://localhost:4321). Reads the one-time credential files generated by
// create-prod-admin.ts / create-prod-client.ts — never prints secrets.
//
// Usage:
//   npx tsx scripts/verify-onboarding.ts \
//     --admin credentials/admin-login.json \
//     --lucia credentials/lucia-login.json \
//     [--base http://localhost:4321]

const BASE = (() => {
  const idx = process.argv.indexOf("--base");
  return idx >= 0 ? process.argv[idx + 1] : "http://localhost:4321";
})();

function readArg(name: string): string | undefined {
  const idx = process.argv.indexOf(name);
  return idx >= 0 ? process.argv[idx + 1] : undefined;
}

function creds(path: string): { email: string; password: string } {
  if (!existsSync(path)) {
    console.error(`Missing credentials file: ${path}`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

let pass = 0;
let fail = 0;
const failures: string[] = [];

function check(name: string, ok: boolean, extra = "") {
  if (ok) {
    pass++;
    console.log(`PASS ${name}`);
  } else {
    fail++;
    failures.push(name);
    console.log(`FAIL ${name}${extra ? ` — ${extra}` : ""}`);
  }
}

function inText(hay: string, needle: string): boolean {
  return hay.includes(needle);
}

async function login(email: string, password: string): Promise<string> {
  const res = await fetch(`${BASE}/api/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password }),
    redirect: "manual",
  });
  const cookie = res.headers.get("set-cookie") || "";
  return cookie.split(";")[0] || "";
}

async function get(path: string, cookie: string): Promise<{ status: number; body: string }> {
  const res = await fetch(`${BASE}${path}`, {
    headers: cookie ? { Cookie: cookie } : {},
    redirect: "manual",
  });
  return { status: res.status, body: await res.text() };
}

async function post(
  path: string,
  cookie: string,
  json?: unknown,
  form?: FormData
): Promise<{ status: number; body: string }> {
  const headers: Record<string, string> = {};
  let body: BodyInit | undefined;
  if (json !== undefined) {
    headers["Content-Type"] = "application/json";
    body = JSON.stringify(json);
  } else if (form) {
    body = form;
  }
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { ...headers, ...(cookie ? { Cookie: cookie } : {}) },
    body,
    redirect: "manual",
  });
  return { status: res.status, body: await res.text() };
}

async function main() {
  const adminPath = readArg("--admin");
  const luciaPath = readArg("--lucia");
  if (!adminPath || !luciaPath) {
    console.error("USAGE: --admin <creds.json> --lucia <creds.json> [--base url]");
    process.exit(1);
  }
  const adminCreds = creds(adminPath);
  const luciaCreds = creds(luciaPath);

  // ─── ADMIN ──────────────────────────────────────────────────────────────
  console.log("== Admin (PK Business Services) ==");
  const adminCookie = await login(adminCreds.email, adminCreds.password);
  check("admin login returns session cookie", adminCookie.startsWith("pk_session="));

  let r = await get("/api/admin/clients", adminCookie);
  check("admin lists clients", r.status === 200);
  check("admin sees Lucia's tenant", r.status === 200 && inText(r.body, "EL MALINOWSKI CONSULTING LLC"));

  r = await get("/api/admin/services", adminCookie);
  check("admin lists service catalog", r.status === 200);
  check(
    "catalog has QuickBooks Cleanup ACTIVE",
    r.status === 200 &&
      inText(r.body, '"slug":"quickbooks-cleanup"') &&
      inText(r.body, '"status":"ACTIVE"')
  );
  check(
    "catalog has Inventory Support INACTIVE",
    r.status === 200 &&
      inText(r.body, '"slug":"inventory-support"') &&
      inText(r.body, '"status":"INACTIVE"')
  );

  r = await get("/api/admin/requests", adminCookie);
  check("admin lists requests", r.status === 200);

  r = await get("/admin/dashboard", adminCookie);
  check("admin /admin/dashboard page reachable", r.status === 200);
  r = await get("/admin/clients", adminCookie);
  check("admin /admin/clients page reachable", r.status === 200);

  r = await get("/api/admin/clients", "");
  check("unauthenticated admin API rejected", r.status >= 400);

  // ─── LUCIA (client) ─────────────────────────────────────────────────────
  console.log("== Lucia (EL MALINOWSKI CONSULTING LLC) ==");
  const luciaCookie = await login(luciaCreds.email, luciaCreds.password);
  check("Lucia login returns session cookie", luciaCookie.startsWith("pk_session="));

  r = await get("/api/auth/session", luciaCookie);
  check(
    "session role is CLIENT with OWNER membership",
    r.status === 200 && inText(r.body, '"role":"CLIENT"') && inText(r.body, '"role":"OWNER"')
  );
  check(
    "Lucia sees only her own business",
    r.status === 200 &&
      inText(r.body, "EL MALINOWSKI CONSULTING LLC") &&
      !inText(r.body, "Acme")
  );

  r = await get("/api/portal/dashboard", luciaCookie);
  check("Lucia portal dashboard reachable", r.status === 200, r.body.slice(0, 120));

  r = await get("/api/portal/services", luciaCookie);
  check("Lucia sees active catalog", r.status === 200 && inText(r.body, '"slug":"quickbooks-cleanup"'));
  check(
    "inactive service NOT in Lucia's catalog",
    r.status === 200 && !inText(r.body, "inventory-support")
  );

  r = await post(
    "/api/portal/requests",
    luciaCookie,
    { serviceSlug: "quickbooks-cleanup", description: "Engagement 1 — QuickBooks cleanup for cleanup client #1 (first 6 months)." }
  );
  check("Lucia creates QuickBooks Cleanup request", r.status >= 200 && r.status < 300, r.body);
  const qbId = (r.body.match(/"id":"([^"]+)"/) || [])[1];

  r = await post(
    "/api/portal/requests",
    luciaCookie,
    { serviceSlug: "inventory-support", description: "should be rejected" }
  );
  check("inactive service selection rejected (400)", r.status >= 400, String(r.status));

  r = await post(
    "/api/portal/requests",
    luciaCookie,
    { serviceSlug: "monthly-bookkeeping", description: "Engagement 2 — Monthly bookkeeping support starting next month." }
  );
  check("Lucia creates second ACTIVE service request", r.status >= 200 && r.status < 300, r.body);
  const mbId = (r.body.match(/"id":"([^"]+)"/) || [])[1];

  r = await get("/api/portal/requests", luciaCookie);
  check(
    "Lucia's request list contains her requests only",
    r.status === 200 &&
      inText(r.body, "QuickBooks Cleanup") &&
      inText(r.body, "Monthly Bookkeeping") &&
      !inText(r.body, "Acme") &&
      !inText(r.body, "cmtknv1wv")
  );

  // Tenant isolation: Lucia cannot read the demo tenant's request.
  r = await get("/api/portal/requests/cmtknv1wv000c04jpm4bdvfkg", luciaCookie);
  check("Lucia cannot read another tenant's request", r.status >= 400, String(r.status));

  // OWNER capability: manage team (member list readable).
  r = await get("/api/portal/members", luciaCookie);
  check("Lucia (OWNER) can read her team members", r.status === 200);

  // Lucia cannot reach admin.
  r = await get("/api/admin/clients", luciaCookie);
  check("Lucia blocked from admin /clients", r.status >= 400, String(r.status));
  r = await get("/api/admin/requests", luciaCookie);
  check("Lucia blocked from admin /requests", r.status >= 400, String(r.status));
  r = await get("/api/admin/services", luciaCookie);
  check("Lucia blocked from admin /services", r.status >= 400, String(r.status));
  if (qbId) {
    r = await post(`/api/admin/requests/${qbId}/reply`, luciaCookie, { body: "impersonation" });
    check("Lucia cannot use staff reply endpoint", r.status >= 400, String(r.status));
  }

  // Admin sees Lucia's requests with the selected service stored.
  if (qbId) {
    r = await get(`/api/admin/requests/${qbId}`, adminCookie);
    check(
      "admin sees Lucia's request detail (service stored)",
      r.status === 200 && inText(r.body, "QuickBooks Cleanup")
    );
  }
  if (mbId) {
    r = await get(`/api/admin/requests/${mbId}`, adminCookie);
    check(
      "admin sees second request with stored service",
      r.status === 200 && inText(r.body, "Monthly Bookkeeping")
    );
  }

  // Public catalog page (signed-out) still shows active services only.
  r = await get("/api/portal/services", "");
  check("signed-out catalog request works (public services)", r.status === 200);

  console.log("");
  console.log(`SUMMARY PASS: ${pass}  FAIL: ${fail}`);
  if (fail > 0) {
    console.log("Failed:", failures.join(" | "));
    process.exit(1);
  }
}

main().catch((e) => {
  console.error("VERIFY_ERROR:", e.message);
  process.exit(1);
});
